name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for reporting your first issue!  I appreciate your interest and making this repo better!'' first issue'
        pr-message: 'Thank you for your first PR!  I appreciate your interest and time to make contributions!'' first pr'
